# Generated by Django 5.2.8 on 2025-11-12 06:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.IntegerField(verbose_name='ความดันบน')),
                ('blood_pressure_diastolic', models.IntegerField(verbose_name='ความดันล่าง')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ส่วนสูง (cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='น้ำหนัก (kg)')),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='เส้นรอบเอว (cm)')),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Cholesterol (mg/dL)')),
                ('ldl', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='LDL (mg/dL)')),
                ('hdl', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='HDL (mg/dL)')),
                ('fbs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='FBS (mg/dL)')),
                ('triglycerides', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Triglycerides (mg/dL)')),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='BMI')),
                ('fat_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='เปอร์เซ็นต์ไขมัน')),
                ('visceral_fat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ไขมันในช่องท้อง')),
                ('muscle_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='เปอร์เซ็นต์กล้ามเนื้อ')),
                ('bmr', models.IntegerField(verbose_name='อัตราการเผาผลาญ BMR')),
                ('body_age', models.IntegerField(verbose_name='อายุร่างกาย')),
                ('recorded_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='วันที่บันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
