# Generated by Django 5.2.8 on 2025-11-12 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('health_record_add', 'Health Record Added'), ('health_record_update', 'Health Record Updated'), ('password_reset', 'Password Reset'), ('status_change', 'Status Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=100, verbose_name='ชื่อ')),
                ('lastname', models.CharField(blank=True, default='', max_length=100, verbose_name='นามสกุล')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง')], default='male', max_length=10, verbose_name='เพศ')),
                ('age', models.IntegerField(blank=True, default=30, verbose_name='อายุ')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='รูปโปรไฟล์')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อเล่น')),
                ('role', models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin'), ('superuser', 'Super User')], default='normal', max_length=20)),
                ('is_active_status', models.BooleanField(default=False, verbose_name='สถานะการใช้งาน')),
                ('is_banned', models.BooleanField(default=False, verbose_name='ถูกแบน')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='เปิดใช้ MFA')),
                ('mfa_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
