# Generated by Django 5.2.8 on 2025-11-15 13:11

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profiles/', validators=[accounts.validators.validate_image_file], verbose_name='รูปโปรไฟล์'),
        ),
    ]
